{
  @davidberneda

  https://github.com/Steema/MotoGP

}
unit TeeTire;

interface

// IA Generated

type
  TTyreModel = class
  private
    // Core physical properties
    FMass: Double;               // Mass in kg (e.g., 4.5 kg)
    FSpecificHeatCap: Double;    // cp in J/(kg*K) (e.g., 1650 for racing rubber)
    FSurfaceArea: Double;        // Exposed area to air in m²
    FContactPatchArea: Double;   // Tyre footprint area in m²

    // Thermal State
    FTemperature: Double;        // Current temperature in °C

    // Heat transfer coefficients (tweakable empirical values)
    FConductionCoef: Double;     // Heat transfer rate to asphalt
    FBaseConvectionCoef: Double; // Base air cooling rate

    function CalculateConvectionCoef(BikeSpeed: Double): Double;
  public
    constructor Create;

    procedure UpdateThermodynamics(
      dt: Double;                // Time delta (seconds)
      SlipForce: Double;         // Combined tire grip force (Newtons)
      SlipVelocity: Double;      // Relative sliding velocity (m/s)
      VerticalLoad: Double;      // Vertical load on the wheel (Newtons)
      AngularVelocity: Double;   // Wheel speed (rad/s)
      BikeSpeed: Double;         // Bike speed over ground (m/s)
      AmbientTemp: Double;       // Ambient air temperature (°C)
      TrackTemp: Double          // Track surface temperature (°C)
    );

    property Temperature: Double read FTemperature;
  end;

implementation

uses
  Math;

constructor TTyreModel.Create;
begin
  inherited;
  // Standard initialization values for a racing tyre
  FMass := 4.5;
  FSpecificHeatCap := 1650.0;
  FSurfaceArea := 0.55;
  FContactPatchArea := 0.015; // Moto contact patches are small
  FTemperature := 20.0;       // Cold start temperature

  FConductionCoef := 15.0;    // Conduction coefficient with asphalt
  FBaseConvectionCoef := 12.0; // Base convection coefficient
end;

function TTyreModel.CalculateConvectionCoef(BikeSpeed: Double): Double;
begin
  // Air cooling increases non-linearly with airspeed
  // Approximated using the 0.8 power law rule for turbulent flow
  Result := FBaseConvectionCoef + (5.0 * Power(Max(0.1, BikeSpeed), 0.8));
end;

procedure TTyreModel.UpdateThermodynamics(
  dt, SlipForce, SlipVelocity, VerticalLoad, AngularVelocity,
  BikeSpeed, AmbientTemp, TrackTemp: Double);
var
  Q_friction, Q_carcass, Q_convection, Q_conduction, Q_total: Double;
  ConvectionCoef: Double;
  DeltaTemp: Double;
  KHysteresis: Double;
begin
  if dt <= 0 then Exit;

  // 1. HEAT GENERATION
  // Pure friction generated by slip/sliding (Watts = Joules/second)
  Q_friction := SlipForce * SlipVelocity;

  // Internal carcass flex heat (structural hysteresis)
  KHysteresis := 0.00005; // Empirical tuning constant
  Q_carcass := KHysteresis * AngularVelocity * VerticalLoad;

  // 2. HEAT DISSIPATION (COOLING)
  // Convection with surrounding air
  ConvectionCoef := CalculateConvectionCoef(BikeSpeed);
  Q_convection := ConvectionCoef * FSurfaceArea * (FTemperature - AmbientTemp);

  // Direct thermal conduction into the track surface
  Q_conduction := FConductionCoef * FContactPatchArea * (FTemperature - TrackTemp);

  // 3. THERMAL BALANCE
  // Net Heat = Generated - Dissipated
  Q_total := (Q_friction + Q_carcass) - (Q_convection + Q_conduction);

  // 4. TEMPERATURE DELTA FOR THIS TICK
  // dT = (Q_total / (m * cp)) * dt
  DeltaTemp := (Q_total / (FMass * FSpecificHeatCap)) * dt;

  // Apply thermal delta
  FTemperature := FTemperature + DeltaTemp;

  // Safety clamp to prevent physics engine explosions or absolute zero readings
  FTemperature := EnsureRange(FTemperature, -20.0, 200.0);
end;

type
  TTrailBrakingSystem = class
  public
    { Calculates the actual available braking force in Newtons based on the
      Friction Ellipse principle as the bike leans towards the apex }
    class function CalculateAvailableBraking(
      RequestedBrakeForce: Double; // Player brake input translated to Newtons (e.g., 0 to 3300 N)
      CentrifugalForce: Double;    // Current lateral cornering force (N) from physics (m * v² / R)
      FrontVerticalLoad: Double;   // Current vertical load on the front tire (N)
      FrontTyreGripCoef: Double    // Current front tire friction coefficient (mu) from thermal module
    ): Double;
  end;

class function TTrailBrakingSystem.CalculateAvailableBraking(
  RequestedBrakeForce, CentrifugalForce, FrontVerticalLoad, FrontTyreGripCoef: Double): Double;
var
  MaxTotalGrip: Double;
  AvailableBrakingForce: Double;
begin
  // 1. Calculate the absolute total grip capacity of the front tire footprint
  // This represents the radius of our Friction Ellipse
  MaxTotalGrip := FrontVerticalLoad * FrontTyreGripCoef;

  // Safety Clamp: If cornering forces already exceed total grip,
  // the tire has completely washed out. Zero braking capacity left.
  if CentrifugalForce >= MaxTotalGrip then
  begin
    Result := 0.0;
    Exit;
  end;

  // 2. Apply the Friction Ellipse Theorem (Pythagorean rearrangement)
  // Calculates how many Newtons of grip are left exclusively for longitudinal braking
  AvailableBrakingForce := Sqrt(Sqr(MaxTotalGrip) - Sqr(CentrifugalForce));

  // 3. Throttle the player's request
  // If the player asks for 3000N but cornering loads only leave 1200N available,
  // the simulator clamps the output to 1200N.
  // (Exceeding this value in your physics loop should trigger a front wheel lockup/lowside)
  Result := Min(RequestedBrakeForce, AvailableBrakingForce);
end;

end.
